import { ImageSlider } from '../components/image-slider';
import { PlanningGuide } from '../components/planning-guide';
import { CelebrationGallery } from '../components/celebration-gallery';
import { LanguageToggle } from '../components/language-toggle';
import { ShlokaSection } from '../components/shloka-section';
import { BusinessSchema } from '../components/business-schema';

export default function Home() {
  return <>
  <BusinessSchema />
  <a className="skip-link" href="#main">Skip to content</a>
  <div className="location-bar">SHYAMA COMPLEX <span>•</span> EKANGAR DIH, NALANDA</div>
  <header className="header">
    <a className="brand" href="#home" aria-label="Shyama Utsav Hall home"><img src="/assets/brand-mark.png" width="54" height="54" alt="" /><span>Shyama Utsav Hall<small>A PLACE FOR YOUR CELEBRATIONS</small></span></a>
    <nav aria-label="Main navigation"><a href="#venue" data-hi="स्थान">The venue</a><a href="#celebrations" data-hi="समारोह">Celebrations</a><a href="#gallery" data-hi="गैलरी">Gallery</a><a className="nav-contact" href="#contact" data-hi="मुलाक़ात तय करें ↗">Plan a visit <span aria-hidden="true">↗</span></a><LanguageToggle /></nav>
  </header>
  <main id="main">
    <section className="hero wrap" id="home">
      <div className="hero-copy"><p className="eyebrow" data-hi="आपका अवसर • आपके लोग • आपकी यादें">YOUR OCCASION. YOUR PEOPLE. YOUR MEMORIES.</p><h1 data-hi="नालंदा में<br />आपका <em>विवाह और समारोह स्थल।</em>">Your wedding &amp;<br />banquet hall<br /><em>in Nalanda.</em></h1><p className="intro" data-hi="अपने प्रियजनों के साथ श्यामा उत्सव हॉल में खुशियाँ मनाएँ। शादियों, पारिवारिक मिलन और यादगार समारोहों के लिए एक खूबसूरत जगह।">Bring your loved ones together at Shyama Utsav Hall. A place for weddings, family gatherings, and the celebrations that mean the most.</p><div className="actions"><a className="button" href="#contact" data-hi="अपना समारोह तय करें ↗">Let’s plan your celebration <span aria-hidden="true">↗</span></a><a className="text-link" href="tel:+919934210304" data-hi="हमारी टीम को कॉल करें">Call our team</a></div><p className="hero-location" data-hi="आशीर्वाद अस्पताल के पास · एकंगर डीह, बिहार">Near Asirwad Hospital · Ekangar Dih, Bihar</p></div>
      <ImageSlider variant="hero" /></section>
    <div className="occasion-strip" aria-label="Celebrations"><span>Weddings</span><b aria-hidden="true">✧</b><span>Receptions</span><b aria-hidden="true">✧</b><span>Engagements</span><b aria-hidden="true">✧</b><span>Family celebrations</span></div>
    <section className="section wrap venue" id="venue"><div><p className="eyebrow" data-hi="श्यामा उत्सव हॉल में आपका स्वागत है">WELCOME TO SHYAMA UTSAV HALL</p><h2 data-hi="घर के पास।<br /><em>दिल के करीब।</em>">Close to home.<br /><em>Close to your heart.</em></h2></div><div><p className="body-large" data-hi="आपका समारोह एक बातचीत से शुरू होता है।">Your celebration starts with a conversation.</p><p data-hi="नालंदा के एकंगर डीह स्थित श्यामा कॉम्प्लेक्स में हमारा हॉल शादियों, रिसेप्शन, सगाई, जन्मदिन और पारिवारिक समारोहों के लिए उपलब्ध है।">Located at Shyama Complex in Ekangar Dih, Nalanda, our hall welcomes enquiries for weddings, receptions, engagements, birthdays, and family functions.</p><p data-hi="अपनी तारीख, मेहमानों की संख्या और अपनी ज़रूरतें हमें बताएँ। हमारी टीम हॉल, बैठने की व्यवस्था और सेवा विकल्पों पर आपकी मदद करेगी।">Tell us your date, guest count, and what you have in mind. Our team will help you discuss the hall, seating arrangements, and service options for your occasion.</p><a className="text-link" href="#contact" data-hi="जगह देखने आएँ ↗">Come and see the space <span aria-hidden="true">↗</span></a></div></section>
    <section className="celebrations section" id="celebrations"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">EVERY GATHERING HAS A STORY</p><h2>Make room for <em>yours.</em></h2></div><p>From a new beginning to another year together,<br />let’s talk about your next occasion.</p></div><div className="event-grid"><article><span className="number">01 /</span><h3>Weddings & receptions</h3><p>Bring family and friends together for your wedding ceremony or reception. Discuss your plans with our team.</p></article><article><span className="number">02 /</span><h3>Engagements & milestones</h3><p>A ring ceremony, an anniversary, a beautiful new chapter. Plan a gathering around the people who matter.</p></article><article><span className="number">03 /</span><h3>Birthdays & family functions</h3><p>Celebrate birthdays and family occasions with a setup suited to your gathering.</p></article></div></div></section>
    <section className="section wrap services" id="services"><div><p className="eyebrow">THE DETAILS THAT BRING IT TOGETHER</p><h2>Your celebration,<br /><em>thoughtfully planned.</em></h2><p>Discuss individual services or a package for your event. Our team will confirm availability, inclusions, and a quotation based on your requirements.</p><a className="text-link" href="https://wa.me/919934210304?text=Hello%2C%20I%20would%20like%20to%20discuss%20an%20event%20at%20Shyama%20Utsav%20Hall.">Discuss options on WhatsApp <span aria-hidden="true">↗</span></a></div><div className="service-list"><article><span>01</span><div><h3>Hall & seating</h3><p>Tell us your guest count and preferred arrangement. Ask our team about capacity and event suitability.</p></div></article><article><span>02</span><div><h3>Food & catering</h3><p>Discuss menu choices, guest numbers, and service style for your celebration.</p></div></article><article><span>03</span><div><h3>Decoration & setup</h3><p>Share your ideas for the stage, entrance, flowers, lighting, and theme.</p></div></article><article><span>04</span><div><h3>Event support</h3><p>Ask about coordination, photography, entertainment, and other support available for your date.</p></div></article></div></section>
    <section className="section gallery-section" id="gallery"><div className="wrap"><div className="section-heading"><div><p className="eyebrow" data-hi="समारोह की झलकियाँ">THE CELEBRATION EDIT</p><h2 data-hi="थोड़ी प्रेरणा।<br /><em>अनगिनत संभावनाएँ।</em>">A little inspiration.<br /><em>A world of possibilities.</em></h2></div><p data-hi="अपने खास दिन के लिए विचार देखें।<br />ये AI से बनाई गई प्रेरणात्मक तस्वीरें हैं; असली हॉल की तस्वीरें जल्द आएँगी।">Explore ideas for your special day.<br />AI-generated inspiration images; actual venue photos coming soon.</p></div><ImageSlider /><CelebrationGallery /><p className="gallery-footnote" data-hi="कोई विवरण पसंद आया? अपने समारोह की संभावनाओं पर हमारी टीम से बात करें।">Love a detail? Share it with our team to discuss possibilities for your event.</p></div></section>
    <PlanningGuide /><section className="section wrap contact" id="contact"><div><p className="eyebrow">LET’S MAKE IT AN OCCASION</p><h2>It starts with<br /><em>“save the date.”</em></h2><p>Have a date in mind? Call or WhatsApp us to discuss availability, guest count, packages, and pricing.</p><div className="actions"><a className="button" href="tel:+919934210304">Call 99342 10304 <span aria-hidden="true">↗</span></a><a className="button secondary" href="https://wa.me/919934210304?text=Hello%2C%20I%20would%20like%20to%20enquire%20about%20Shyama%20Utsav%20Hall.">WhatsApp us</a></div><p className="secondary-number">You can also call <a href="tel:+919534765781">95347 65781</a></p><p className="fine-print">Availability, services, prices, and bookings are confirmed by our team.</p></div><aside className="visit-card"><p className="eyebrow">COME SAY HELLO</p><h3>Shyama Utsav Hall</h3><address>Shyama Complex<br />Near Asirwad Hospital<br />Ekangar Dih, Nalanda<br />Bihar 801301</address><a className="text-link" href="https://www.google.com/maps/dir/?api=1&amp;destination=25.2171816%2C85.2577987" target="_blank" rel="noopener noreferrer">Get directions <span aria-hidden="true">↗</span></a><p>Please call or WhatsApp before visiting so we can confirm a suitable time.</p></aside></section>
    <ShlokaSection />
  </main>
  <footer className="footer"><div className="wrap"><a className="footer-brand" href="#home">Shyama Utsav Hall<small>AT SHYAMA COMPLEX</small></a><p>For the moments you’ll always remember.</p><span>© <span>{new Date().getFullYear()}</span> Shyama Complex</span></div></footer>
  <div className="mobile-contact"><a href="tel:+919934210304">Call our team</a><a href="https://wa.me/919934210304">WhatsApp</a></div>
</>;
}
